In [3]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [4]:
data = pd.DataFrame({
    'Transmission': ['Automatic', 'Manual', 'Automatic', 'Manual'],
    'Color': ['Red', 'Blue', 'Green', 'Red']})
data

  Transmission  Color
0    Automatic    Red
1       Manual   Blue
2    Automatic  Green
3       Manual    Red

In [7]:
df=LabelEncoder()
data["Transmission"]=df.fit_transform(data["Transmission"])

In [8]:
data = pd.get_dummies(data, columns=['Color'], drop_first=True)

In [13]:
data

   Transmission  Color_Green  Color_Red
0             0        False       True
1             1        False      False
2             0         True      False
3             1        False       True