In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv(r"C:\Users\mallikarjun\OneDrive\Documents\Book1.csv")
data

   Location
0  New York
1  new york
2  NEW YORK

In [5]:
data["Location"].unique()

array(['New York', 'new york', 'NEW YORK'], dtype=object)

In [8]:
data["Location"] = data["Location"].str.strip()
data

   Location
0  New York
1  new york
2  NEW YORK

In [9]:
data["Location"]=data["Location"].str.lower()
data

   Location
0  new york
1  new york
2  new york

In [12]:
data["Location"].unique()

array(['new york'], dtype=object)